[package]
name = "posemir_cli"
version = "0.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
posemir = { path = "../posemir" }
clap = { version = "3.0.9", features = ["derive"] }
